version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: tasksapp
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: camilo
      MYSQL_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - db
